name: airoco_check

on:
  schedule:
    - cron: '30 11 * * 1-5'  # JST 20:30 は UTC 11:30、月〜金 (1-5)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        AIROCO_ID: ${{ secrets.AIROCO_ID }}
        AIROCO_API_KEY: ${{ secrets.AIROCO_API_KEY }}
        AIROCO_API_BASE_URL: ${{ secrets.AIROCO_API_BASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/installed/requirements.txt  # 依存関係を一括インストール
      - name: Run script
        run: |
          python backend/main.py
