name: airoco_check

on:
  schedule:
    - cron: '50 10 * * 1-5'  # JST 19:50 は UTC 10:50、月〜金 (1-5)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        AIROCO_ID: ${{ secrets.AIROCO_ID }}
        AIROCO_API_KEY: ${{ secrets.AIROCO_API_KEY }}
        AIROCO_API_BASE_URL: ${{ secrets.AIROCO_API_BASE_URL }}
        SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
        SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
        SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/installed/requirements.txt  # 依存関係を一括インストール
      - name: Run script
        run: |
          python backend/main.py
